sudo: required
services:
  - docker

before_install:
  - docker build -t jimmy2952/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jimmy2952/react-test npm test

after_success:
  - docker build -t jimmy2952/multi-client ./client
  - docker build -t jimmy2952/multi-nginx ./nginx
  - docker build -t jimmy2952/multi-server ./server
  - docker build -t jimmy2952/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push jimmy2952/multi-client
  - docker push jimmy2952/multi-nginx
  - docker push jimmy2952/multi-server
  - docker push jimmy2952/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-060813237894'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY